version: '3.8'

services:
  mysql-dev:
    image: sdpx/db
    container_name: db-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - dev

  flask-app-dev:
    image: sdpx/api 
    container_name: api-dev
    restart: always
    depends_on:
      - mysql-dev
    ports:
      - "8081:5000"
    environment:
      DB_HOST: db-dev
      DB_PORT: 3306
    env_file:
      - ./backend/.env
    networks:
      - dev

volumes:
  mysql_data_dev:

networks:
  dev:
    driver: bridge
