version: '3.8'

services:
  mysql-test:
    image: sdpx/db
    container_name: db-test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql
    networks:
      - test

  flask-app-test:
    image: sdpx/api 
    container_name: api-test
    restart: always
    depends_on:
      - mysql-test
    ports:
      - "8082:5000"
    environment:
      DB_HOST: db-test
      DB_PORT: 3306
    env_file:
      - ./backend/.env
    networks:
      - test

volumes:
  mysql_data_test:

networks:
  test:
    driver: bridge
